/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StocksRouteImport } from './routes/stocks'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SortiesLocalesRouteImport } from './routes/sorties-locales'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RapportsRouteImport } from './routes/rapports'
import { Route as ProduitsTarifsRouteImport } from './routes/produits-tarifs'
import { Route as ProduitsObjectifsRouteImport } from './routes/produits-objectifs'
import { Route as ProduitsRouteImport } from './routes/produits'
import { Route as PaysRouteImport } from './routes/pays'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LaboratoiresRouteImport } from './routes/laboratoires'
import { Route as ImportRouteImport } from './routes/import'
import { Route as GrossistesRouteImport } from './routes/grossistes'
import { Route as FournisseursRouteImport } from './routes/fournisseurs'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AgencesRouteImport } from './routes/agences'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SortiesLocalesIndexRouteImport } from './routes/sorties-locales.index'
import { Route as SortiesLocalesVuePanoramiqueRouteImport } from './routes/sorties-locales.vue-panoramique'
import { Route as SortiesLocalesVentesUnRouteImport } from './routes/sorties-locales.ventes-un'
import { Route as SortiesLocalesVentesCaRouteImport } from './routes/sorties-locales.ventes-ca'
import { Route as SortiesLocalesStocksPaysRouteImport } from './routes/sorties-locales.stocks-pays'
import { Route as SortiesLocalesStocksEnCoursRouteImport } from './routes/sorties-locales.stocks-en-cours'
import { Route as SortiesLocalesObjectifsPaysRouteImport } from './routes/sorties-locales.objectifs-pays'
import { Route as SortiesLocalesObjectifsAnfRouteImport } from './routes/sorties-locales.objectifs-anf'
import { Route as SortiesLocalesEvolutionUnRouteImport } from './routes/sorties-locales.evolution-un'
import { Route as SortiesLocalesEvolutionCaRouteImport } from './routes/sorties-locales.evolution-ca'

const StocksRoute = StocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SortiesLocalesRoute = SortiesLocalesRouteImport.update({
  id: '/sorties-locales',
  path: '/sorties-locales',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RapportsRoute = RapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitsTarifsRoute = ProduitsTarifsRouteImport.update({
  id: '/produits-tarifs',
  path: '/produits-tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitsObjectifsRoute = ProduitsObjectifsRouteImport.update({
  id: '/produits-objectifs',
  path: '/produits-objectifs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitsRoute = ProduitsRouteImport.update({
  id: '/produits',
  path: '/produits',
  getParentRoute: () => rootRouteImport,
} as any)
const PaysRoute = PaysRouteImport.update({
  id: '/pays',
  path: '/pays',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LaboratoiresRoute = LaboratoiresRouteImport.update({
  id: '/laboratoires',
  path: '/laboratoires',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const GrossistesRoute = GrossistesRouteImport.update({
  id: '/grossistes',
  path: '/grossistes',
  getParentRoute: () => rootRouteImport,
} as any)
const FournisseursRoute = FournisseursRouteImport.update({
  id: '/fournisseurs',
  path: '/fournisseurs',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencesRoute = AgencesRouteImport.update({
  id: '/agences',
  path: '/agences',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SortiesLocalesIndexRoute = SortiesLocalesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SortiesLocalesRoute,
} as any)
const SortiesLocalesVuePanoramiqueRoute =
  SortiesLocalesVuePanoramiqueRouteImport.update({
    id: '/vue-panoramique',
    path: '/vue-panoramique',
    getParentRoute: () => SortiesLocalesRoute,
  } as any)
const SortiesLocalesVentesUnRoute = SortiesLocalesVentesUnRouteImport.update({
  id: '/ventes-un',
  path: '/ventes-un',
  getParentRoute: () => SortiesLocalesRoute,
} as any)
const SortiesLocalesVentesCaRoute = SortiesLocalesVentesCaRouteImport.update({
  id: '/ventes-ca',
  path: '/ventes-ca',
  getParentRoute: () => SortiesLocalesRoute,
} as any)
const SortiesLocalesStocksPaysRoute =
  SortiesLocalesStocksPaysRouteImport.update({
    id: '/stocks-pays',
    path: '/stocks-pays',
    getParentRoute: () => SortiesLocalesRoute,
  } as any)
const SortiesLocalesStocksEnCoursRoute =
  SortiesLocalesStocksEnCoursRouteImport.update({
    id: '/stocks-en-cours',
    path: '/stocks-en-cours',
    getParentRoute: () => SortiesLocalesRoute,
  } as any)
const SortiesLocalesObjectifsPaysRoute =
  SortiesLocalesObjectifsPaysRouteImport.update({
    id: '/objectifs-pays',
    path: '/objectifs-pays',
    getParentRoute: () => SortiesLocalesRoute,
  } as any)
const SortiesLocalesObjectifsAnfRoute =
  SortiesLocalesObjectifsAnfRouteImport.update({
    id: '/objectifs-anf',
    path: '/objectifs-anf',
    getParentRoute: () => SortiesLocalesRoute,
  } as any)
const SortiesLocalesEvolutionUnRoute =
  SortiesLocalesEvolutionUnRouteImport.update({
    id: '/evolution-un',
    path: '/evolution-un',
    getParentRoute: () => SortiesLocalesRoute,
  } as any)
const SortiesLocalesEvolutionCaRoute =
  SortiesLocalesEvolutionCaRouteImport.update({
    id: '/evolution-ca',
    path: '/evolution-ca',
    getParentRoute: () => SortiesLocalesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agences': typeof AgencesRoute
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/fournisseurs': typeof FournisseursRoute
  '/grossistes': typeof GrossistesRoute
  '/import': typeof ImportRoute
  '/laboratoires': typeof LaboratoiresRoute
  '/login': typeof LoginRoute
  '/parametres': typeof ParametresRoute
  '/pays': typeof PaysRoute
  '/produits': typeof ProduitsRoute
  '/produits-objectifs': typeof ProduitsObjectifsRoute
  '/produits-tarifs': typeof ProduitsTarifsRoute
  '/rapports': typeof RapportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sorties-locales': typeof SortiesLocalesRouteWithChildren
  '/stats': typeof StatsRoute
  '/stocks': typeof StocksRoute
  '/sorties-locales/evolution-ca': typeof SortiesLocalesEvolutionCaRoute
  '/sorties-locales/evolution-un': typeof SortiesLocalesEvolutionUnRoute
  '/sorties-locales/objectifs-anf': typeof SortiesLocalesObjectifsAnfRoute
  '/sorties-locales/objectifs-pays': typeof SortiesLocalesObjectifsPaysRoute
  '/sorties-locales/stocks-en-cours': typeof SortiesLocalesStocksEnCoursRoute
  '/sorties-locales/stocks-pays': typeof SortiesLocalesStocksPaysRoute
  '/sorties-locales/ventes-ca': typeof SortiesLocalesVentesCaRoute
  '/sorties-locales/ventes-un': typeof SortiesLocalesVentesUnRoute
  '/sorties-locales/vue-panoramique': typeof SortiesLocalesVuePanoramiqueRoute
  '/sorties-locales/': typeof SortiesLocalesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agences': typeof AgencesRoute
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/fournisseurs': typeof FournisseursRoute
  '/grossistes': typeof GrossistesRoute
  '/import': typeof ImportRoute
  '/laboratoires': typeof LaboratoiresRoute
  '/login': typeof LoginRoute
  '/parametres': typeof ParametresRoute
  '/pays': typeof PaysRoute
  '/produits': typeof ProduitsRoute
  '/produits-objectifs': typeof ProduitsObjectifsRoute
  '/produits-tarifs': typeof ProduitsTarifsRoute
  '/rapports': typeof RapportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/stats': typeof StatsRoute
  '/stocks': typeof StocksRoute
  '/sorties-locales/evolution-ca': typeof SortiesLocalesEvolutionCaRoute
  '/sorties-locales/evolution-un': typeof SortiesLocalesEvolutionUnRoute
  '/sorties-locales/objectifs-anf': typeof SortiesLocalesObjectifsAnfRoute
  '/sorties-locales/objectifs-pays': typeof SortiesLocalesObjectifsPaysRoute
  '/sorties-locales/stocks-en-cours': typeof SortiesLocalesStocksEnCoursRoute
  '/sorties-locales/stocks-pays': typeof SortiesLocalesStocksPaysRoute
  '/sorties-locales/ventes-ca': typeof SortiesLocalesVentesCaRoute
  '/sorties-locales/ventes-un': typeof SortiesLocalesVentesUnRoute
  '/sorties-locales/vue-panoramique': typeof SortiesLocalesVuePanoramiqueRoute
  '/sorties-locales': typeof SortiesLocalesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agences': typeof AgencesRoute
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/fournisseurs': typeof FournisseursRoute
  '/grossistes': typeof GrossistesRoute
  '/import': typeof ImportRoute
  '/laboratoires': typeof LaboratoiresRoute
  '/login': typeof LoginRoute
  '/parametres': typeof ParametresRoute
  '/pays': typeof PaysRoute
  '/produits': typeof ProduitsRoute
  '/produits-objectifs': typeof ProduitsObjectifsRoute
  '/produits-tarifs': typeof ProduitsTarifsRoute
  '/rapports': typeof RapportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sorties-locales': typeof SortiesLocalesRouteWithChildren
  '/stats': typeof StatsRoute
  '/stocks': typeof StocksRoute
  '/sorties-locales/evolution-ca': typeof SortiesLocalesEvolutionCaRoute
  '/sorties-locales/evolution-un': typeof SortiesLocalesEvolutionUnRoute
  '/sorties-locales/objectifs-anf': typeof SortiesLocalesObjectifsAnfRoute
  '/sorties-locales/objectifs-pays': typeof SortiesLocalesObjectifsPaysRoute
  '/sorties-locales/stocks-en-cours': typeof SortiesLocalesStocksEnCoursRoute
  '/sorties-locales/stocks-pays': typeof SortiesLocalesStocksPaysRoute
  '/sorties-locales/ventes-ca': typeof SortiesLocalesVentesCaRoute
  '/sorties-locales/ventes-un': typeof SortiesLocalesVentesUnRoute
  '/sorties-locales/vue-panoramique': typeof SortiesLocalesVuePanoramiqueRoute
  '/sorties-locales/': typeof SortiesLocalesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agences'
    | '/change-password'
    | '/forgot-password'
    | '/fournisseurs'
    | '/grossistes'
    | '/import'
    | '/laboratoires'
    | '/login'
    | '/parametres'
    | '/pays'
    | '/produits'
    | '/produits-objectifs'
    | '/produits-tarifs'
    | '/rapports'
    | '/reset-password'
    | '/sorties-locales'
    | '/stats'
    | '/stocks'
    | '/sorties-locales/evolution-ca'
    | '/sorties-locales/evolution-un'
    | '/sorties-locales/objectifs-anf'
    | '/sorties-locales/objectifs-pays'
    | '/sorties-locales/stocks-en-cours'
    | '/sorties-locales/stocks-pays'
    | '/sorties-locales/ventes-ca'
    | '/sorties-locales/ventes-un'
    | '/sorties-locales/vue-panoramique'
    | '/sorties-locales/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agences'
    | '/change-password'
    | '/forgot-password'
    | '/fournisseurs'
    | '/grossistes'
    | '/import'
    | '/laboratoires'
    | '/login'
    | '/parametres'
    | '/pays'
    | '/produits'
    | '/produits-objectifs'
    | '/produits-tarifs'
    | '/rapports'
    | '/reset-password'
    | '/stats'
    | '/stocks'
    | '/sorties-locales/evolution-ca'
    | '/sorties-locales/evolution-un'
    | '/sorties-locales/objectifs-anf'
    | '/sorties-locales/objectifs-pays'
    | '/sorties-locales/stocks-en-cours'
    | '/sorties-locales/stocks-pays'
    | '/sorties-locales/ventes-ca'
    | '/sorties-locales/ventes-un'
    | '/sorties-locales/vue-panoramique'
    | '/sorties-locales'
  id:
    | '__root__'
    | '/'
    | '/agences'
    | '/change-password'
    | '/forgot-password'
    | '/fournisseurs'
    | '/grossistes'
    | '/import'
    | '/laboratoires'
    | '/login'
    | '/parametres'
    | '/pays'
    | '/produits'
    | '/produits-objectifs'
    | '/produits-tarifs'
    | '/rapports'
    | '/reset-password'
    | '/sorties-locales'
    | '/stats'
    | '/stocks'
    | '/sorties-locales/evolution-ca'
    | '/sorties-locales/evolution-un'
    | '/sorties-locales/objectifs-anf'
    | '/sorties-locales/objectifs-pays'
    | '/sorties-locales/stocks-en-cours'
    | '/sorties-locales/stocks-pays'
    | '/sorties-locales/ventes-ca'
    | '/sorties-locales/ventes-un'
    | '/sorties-locales/vue-panoramique'
    | '/sorties-locales/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgencesRoute: typeof AgencesRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  FournisseursRoute: typeof FournisseursRoute
  GrossistesRoute: typeof GrossistesRoute
  ImportRoute: typeof ImportRoute
  LaboratoiresRoute: typeof LaboratoiresRoute
  LoginRoute: typeof LoginRoute
  ParametresRoute: typeof ParametresRoute
  PaysRoute: typeof PaysRoute
  ProduitsRoute: typeof ProduitsRoute
  ProduitsObjectifsRoute: typeof ProduitsObjectifsRoute
  ProduitsTarifsRoute: typeof ProduitsTarifsRoute
  RapportsRoute: typeof RapportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SortiesLocalesRoute: typeof SortiesLocalesRouteWithChildren
  StatsRoute: typeof StatsRoute
  StocksRoute: typeof StocksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stocks': {
      id: '/stocks'
      path: '/stocks'
      fullPath: '/stocks'
      preLoaderRoute: typeof StocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sorties-locales': {
      id: '/sorties-locales'
      path: '/sorties-locales'
      fullPath: '/sorties-locales'
      preLoaderRoute: typeof SortiesLocalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapports': {
      id: '/rapports'
      path: '/rapports'
      fullPath: '/rapports'
      preLoaderRoute: typeof RapportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produits-tarifs': {
      id: '/produits-tarifs'
      path: '/produits-tarifs'
      fullPath: '/produits-tarifs'
      preLoaderRoute: typeof ProduitsTarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produits-objectifs': {
      id: '/produits-objectifs'
      path: '/produits-objectifs'
      fullPath: '/produits-objectifs'
      preLoaderRoute: typeof ProduitsObjectifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produits': {
      id: '/produits'
      path: '/produits'
      fullPath: '/produits'
      preLoaderRoute: typeof ProduitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pays': {
      id: '/pays'
      path: '/pays'
      fullPath: '/pays'
      preLoaderRoute: typeof PaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laboratoires': {
      id: '/laboratoires'
      path: '/laboratoires'
      fullPath: '/laboratoires'
      preLoaderRoute: typeof LaboratoiresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grossistes': {
      id: '/grossistes'
      path: '/grossistes'
      fullPath: '/grossistes'
      preLoaderRoute: typeof GrossistesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fournisseurs': {
      id: '/fournisseurs'
      path: '/fournisseurs'
      fullPath: '/fournisseurs'
      preLoaderRoute: typeof FournisseursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agences': {
      id: '/agences'
      path: '/agences'
      fullPath: '/agences'
      preLoaderRoute: typeof AgencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sorties-locales/': {
      id: '/sorties-locales/'
      path: '/'
      fullPath: '/sorties-locales/'
      preLoaderRoute: typeof SortiesLocalesIndexRouteImport
      parentRoute: typeof SortiesLocalesRoute
    }
    '/sorties-locales/vue-panoramique': {
      id: '/sorties-locales/vue-panoramique'
      path: '/vue-panoramique'
      fullPath: '/sorties-locales/vue-panoramique'
      preLoaderRoute: typeof SortiesLocalesVuePanoramiqueRouteImport
      parentRoute: typeof SortiesLocalesRoute
    }
    '/sorties-locales/ventes-un': {
      id: '/sorties-locales/ventes-un'
      path: '/ventes-un'
      fullPath: '/sorties-locales/ventes-un'
      preLoaderRoute: typeof SortiesLocalesVentesUnRouteImport
      parentRoute: typeof SortiesLocalesRoute
    }
    '/sorties-locales/ventes-ca': {
      id: '/sorties-locales/ventes-ca'
      path: '/ventes-ca'
      fullPath: '/sorties-locales/ventes-ca'
      preLoaderRoute: typeof SortiesLocalesVentesCaRouteImport
      parentRoute: typeof SortiesLocalesRoute
    }
    '/sorties-locales/stocks-pays': {
      id: '/sorties-locales/stocks-pays'
      path: '/stocks-pays'
      fullPath: '/sorties-locales/stocks-pays'
      preLoaderRoute: typeof SortiesLocalesStocksPaysRouteImport
      parentRoute: typeof SortiesLocalesRoute
    }
    '/sorties-locales/stocks-en-cours': {
      id: '/sorties-locales/stocks-en-cours'
      path: '/stocks-en-cours'
      fullPath: '/sorties-locales/stocks-en-cours'
      preLoaderRoute: typeof SortiesLocalesStocksEnCoursRouteImport
      parentRoute: typeof SortiesLocalesRoute
    }
    '/sorties-locales/objectifs-pays': {
      id: '/sorties-locales/objectifs-pays'
      path: '/objectifs-pays'
      fullPath: '/sorties-locales/objectifs-pays'
      preLoaderRoute: typeof SortiesLocalesObjectifsPaysRouteImport
      parentRoute: typeof SortiesLocalesRoute
    }
    '/sorties-locales/objectifs-anf': {
      id: '/sorties-locales/objectifs-anf'
      path: '/objectifs-anf'
      fullPath: '/sorties-locales/objectifs-anf'
      preLoaderRoute: typeof SortiesLocalesObjectifsAnfRouteImport
      parentRoute: typeof SortiesLocalesRoute
    }
    '/sorties-locales/evolution-un': {
      id: '/sorties-locales/evolution-un'
      path: '/evolution-un'
      fullPath: '/sorties-locales/evolution-un'
      preLoaderRoute: typeof SortiesLocalesEvolutionUnRouteImport
      parentRoute: typeof SortiesLocalesRoute
    }
    '/sorties-locales/evolution-ca': {
      id: '/sorties-locales/evolution-ca'
      path: '/evolution-ca'
      fullPath: '/sorties-locales/evolution-ca'
      preLoaderRoute: typeof SortiesLocalesEvolutionCaRouteImport
      parentRoute: typeof SortiesLocalesRoute
    }
  }
}

interface SortiesLocalesRouteChildren {
  SortiesLocalesEvolutionCaRoute: typeof SortiesLocalesEvolutionCaRoute
  SortiesLocalesEvolutionUnRoute: typeof SortiesLocalesEvolutionUnRoute
  SortiesLocalesObjectifsAnfRoute: typeof SortiesLocalesObjectifsAnfRoute
  SortiesLocalesObjectifsPaysRoute: typeof SortiesLocalesObjectifsPaysRoute
  SortiesLocalesStocksEnCoursRoute: typeof SortiesLocalesStocksEnCoursRoute
  SortiesLocalesStocksPaysRoute: typeof SortiesLocalesStocksPaysRoute
  SortiesLocalesVentesCaRoute: typeof SortiesLocalesVentesCaRoute
  SortiesLocalesVentesUnRoute: typeof SortiesLocalesVentesUnRoute
  SortiesLocalesVuePanoramiqueRoute: typeof SortiesLocalesVuePanoramiqueRoute
  SortiesLocalesIndexRoute: typeof SortiesLocalesIndexRoute
}

const SortiesLocalesRouteChildren: SortiesLocalesRouteChildren = {
  SortiesLocalesEvolutionCaRoute: SortiesLocalesEvolutionCaRoute,
  SortiesLocalesEvolutionUnRoute: SortiesLocalesEvolutionUnRoute,
  SortiesLocalesObjectifsAnfRoute: SortiesLocalesObjectifsAnfRoute,
  SortiesLocalesObjectifsPaysRoute: SortiesLocalesObjectifsPaysRoute,
  SortiesLocalesStocksEnCoursRoute: SortiesLocalesStocksEnCoursRoute,
  SortiesLocalesStocksPaysRoute: SortiesLocalesStocksPaysRoute,
  SortiesLocalesVentesCaRoute: SortiesLocalesVentesCaRoute,
  SortiesLocalesVentesUnRoute: SortiesLocalesVentesUnRoute,
  SortiesLocalesVuePanoramiqueRoute: SortiesLocalesVuePanoramiqueRoute,
  SortiesLocalesIndexRoute: SortiesLocalesIndexRoute,
}

const SortiesLocalesRouteWithChildren = SortiesLocalesRoute._addFileChildren(
  SortiesLocalesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgencesRoute: AgencesRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  FournisseursRoute: FournisseursRoute,
  GrossistesRoute: GrossistesRoute,
  ImportRoute: ImportRoute,
  LaboratoiresRoute: LaboratoiresRoute,
  LoginRoute: LoginRoute,
  ParametresRoute: ParametresRoute,
  PaysRoute: PaysRoute,
  ProduitsRoute: ProduitsRoute,
  ProduitsObjectifsRoute: ProduitsObjectifsRoute,
  ProduitsTarifsRoute: ProduitsTarifsRoute,
  RapportsRoute: RapportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SortiesLocalesRoute: SortiesLocalesRouteWithChildren,
  StatsRoute: StatsRoute,
  StocksRoute: StocksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
