/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StocksRouteImport } from './routes/stocks'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as RapportsRouteImport } from './routes/rapports'
import { Route as ProduitsRouteImport } from './routes/produits'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LaboratoiresRouteImport } from './routes/laboratoires'
import { Route as ImportRouteImport } from './routes/import'
import { Route as GrossistesRouteImport } from './routes/grossistes'
import { Route as FournisseursRouteImport } from './routes/fournisseurs'
import { Route as AgencesRouteImport } from './routes/agences'
import { Route as IndexRouteImport } from './routes/index'

const StocksRoute = StocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const RapportsRoute = RapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitsRoute = ProduitsRouteImport.update({
  id: '/produits',
  path: '/produits',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LaboratoiresRoute = LaboratoiresRouteImport.update({
  id: '/laboratoires',
  path: '/laboratoires',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const GrossistesRoute = GrossistesRouteImport.update({
  id: '/grossistes',
  path: '/grossistes',
  getParentRoute: () => rootRouteImport,
} as any)
const FournisseursRoute = FournisseursRouteImport.update({
  id: '/fournisseurs',
  path: '/fournisseurs',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencesRoute = AgencesRouteImport.update({
  id: '/agences',
  path: '/agences',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agences': typeof AgencesRoute
  '/fournisseurs': typeof FournisseursRoute
  '/grossistes': typeof GrossistesRoute
  '/import': typeof ImportRoute
  '/laboratoires': typeof LaboratoiresRoute
  '/login': typeof LoginRoute
  '/parametres': typeof ParametresRoute
  '/produits': typeof ProduitsRoute
  '/rapports': typeof RapportsRoute
  '/stats': typeof StatsRoute
  '/stocks': typeof StocksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agences': typeof AgencesRoute
  '/fournisseurs': typeof FournisseursRoute
  '/grossistes': typeof GrossistesRoute
  '/import': typeof ImportRoute
  '/laboratoires': typeof LaboratoiresRoute
  '/login': typeof LoginRoute
  '/parametres': typeof ParametresRoute
  '/produits': typeof ProduitsRoute
  '/rapports': typeof RapportsRoute
  '/stats': typeof StatsRoute
  '/stocks': typeof StocksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agences': typeof AgencesRoute
  '/fournisseurs': typeof FournisseursRoute
  '/grossistes': typeof GrossistesRoute
  '/import': typeof ImportRoute
  '/laboratoires': typeof LaboratoiresRoute
  '/login': typeof LoginRoute
  '/parametres': typeof ParametresRoute
  '/produits': typeof ProduitsRoute
  '/rapports': typeof RapportsRoute
  '/stats': typeof StatsRoute
  '/stocks': typeof StocksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agences'
    | '/fournisseurs'
    | '/grossistes'
    | '/import'
    | '/laboratoires'
    | '/login'
    | '/parametres'
    | '/produits'
    | '/rapports'
    | '/stats'
    | '/stocks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agences'
    | '/fournisseurs'
    | '/grossistes'
    | '/import'
    | '/laboratoires'
    | '/login'
    | '/parametres'
    | '/produits'
    | '/rapports'
    | '/stats'
    | '/stocks'
  id:
    | '__root__'
    | '/'
    | '/agences'
    | '/fournisseurs'
    | '/grossistes'
    | '/import'
    | '/laboratoires'
    | '/login'
    | '/parametres'
    | '/produits'
    | '/rapports'
    | '/stats'
    | '/stocks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgencesRoute: typeof AgencesRoute
  FournisseursRoute: typeof FournisseursRoute
  GrossistesRoute: typeof GrossistesRoute
  ImportRoute: typeof ImportRoute
  LaboratoiresRoute: typeof LaboratoiresRoute
  LoginRoute: typeof LoginRoute
  ParametresRoute: typeof ParametresRoute
  ProduitsRoute: typeof ProduitsRoute
  RapportsRoute: typeof RapportsRoute
  StatsRoute: typeof StatsRoute
  StocksRoute: typeof StocksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stocks': {
      id: '/stocks'
      path: '/stocks'
      fullPath: '/stocks'
      preLoaderRoute: typeof StocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapports': {
      id: '/rapports'
      path: '/rapports'
      fullPath: '/rapports'
      preLoaderRoute: typeof RapportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produits': {
      id: '/produits'
      path: '/produits'
      fullPath: '/produits'
      preLoaderRoute: typeof ProduitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laboratoires': {
      id: '/laboratoires'
      path: '/laboratoires'
      fullPath: '/laboratoires'
      preLoaderRoute: typeof LaboratoiresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grossistes': {
      id: '/grossistes'
      path: '/grossistes'
      fullPath: '/grossistes'
      preLoaderRoute: typeof GrossistesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fournisseurs': {
      id: '/fournisseurs'
      path: '/fournisseurs'
      fullPath: '/fournisseurs'
      preLoaderRoute: typeof FournisseursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agences': {
      id: '/agences'
      path: '/agences'
      fullPath: '/agences'
      preLoaderRoute: typeof AgencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgencesRoute: AgencesRoute,
  FournisseursRoute: FournisseursRoute,
  GrossistesRoute: GrossistesRoute,
  ImportRoute: ImportRoute,
  LaboratoiresRoute: LaboratoiresRoute,
  LoginRoute: LoginRoute,
  ParametresRoute: ParametresRoute,
  ProduitsRoute: ProduitsRoute,
  RapportsRoute: RapportsRoute,
  StatsRoute: StatsRoute,
  StocksRoute: StocksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
